---
controller_hosts:
  - name: "{{ agw_vm_hostname }}"
    inventory: "{{ demo_azure_inventory_name }}"
    variables:
      cloud: azure
      lb_backend: agw
      ansible_host: "{{ agw_vm_private_ip }}"

  - name: "{{ f5_vm_hostname }}"
    inventory: "{{ demo_azure_inventory_name }}"
    variables:
      cloud: azure
      lb_backend: f5
      ansible_host: "{{ f5_vm_private_ip }}"
